name: python-pipeline

env:
  ARTIFACT_NAME: hello

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python hello.py
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
          
